export const DEGREE = [
    {degree: 'B.A. (Bachelor of Arts)', value: 'B.A. (Bachelor of Arts)', field:[
      {name: 'Literature (English, Hindi, Sanskrit, Regional Languages)',value: 'Literature (English, Hindi, Sanskrit, Regional Languages)'},
      {name: 'History',value: 'History'},
      {name: 'Geography',value: 'Geography'},
      {name: 'Political Science',value: 'Political Science'},
      {name: 'Sociology',value: 'Sociology'},
      {name: 'Psychology',value: 'Psychology'},
      {name: 'Economics',value: 'Economics'},
      {name: 'Philosophy',value: 'Philosophy'},
      {name: 'Anthropology',value: 'Anthropology'},
      {name: 'Archaeology',value: 'Archaeology'},
      {name: 'Journalism & Mass Communication',value: 'Journalism & Mass Communication'},
      {name: 'Fine Arts',value: 'Fine Arts'},
      {name: 'Performing Arts',value: 'Performing Arts'},
      {name: 'Music',value: 'Music'},
      {name: 'Dance',value: 'Dance'},
      {name: 'Theatre',value: 'Theatre'},
    ]},
    {degree: 'B.S.W. (Bachelor of Social Work)', value: 'B.S.W. (Bachelor of Social Work)', field:[]},
    {degree: 'B. Com. (Bachelor of Commerce)', value: 'B. Com. (Bachelor of Commerce)', field:[
        {name: 'Accounting & Finance',value: 'Accounting & Finance'},
        {name: 'Banking & Insurance',value: 'Banking & Insurance'},
        {name: 'Auditing',value: 'Auditing'},
        {name: 'Taxation',value: 'Taxation'},
        {name: 'Economics & Business Studies',value: 'Economics & Business Studies'},
        {name: 'International Business',value: 'International Business'},
        {name: 'E-Commerce',value: 'E-Commerce'},
    ]},
    {degree: 'B.F.A. (Bachelor of Fine Arts)', value: 'B.F.A. (Bachelor of Fine Arts)', field:[
        {name: 'Visual Arts (Painting, Applied Arts, Sculpture, Printmaking)',value: 'Visual Arts (Painting, Applied Arts, Sculpture, Printmaking)'},
        {name: 'Mural Art',value: 'Mural Art'},
        {name: 'Portraiture',value: 'Portraiture'},
        {name: 'Calligraphy',value: 'Calligraphy'},
        {name: 'Design-Oriented Graphic Design, Animation & Multimedia, Photography, Illustration, Industrial Design Basics, Textile Design',
        value: 'Design-Oriented Graphic Design, Animation & Multimedia, Photography, Illustration, Industrial Design Basics, Textile Design'},
        {name: 'Performing Arts (Theatre / Acting, Music, Dance)',
        value: 'Performing Arts (Theatre / Acting, Music, Dance)'},
        {name: 'Visual Communication',value: 'Visual Communication'},
        {name: 'Digital Art & New Media',value: 'Digital Art & New Media'},
        {name: 'Art History & Art Criticism',value: 'Art History & Art Criticism'},
        {name: 'Installation Art',value: 'Installation Art'},
        {name: 'Film & Video Arts',value: 'Film & Video Arts'},
    ]},
    {degree: 'B.Lib.Sc. (Bachelor of Library Science)', value: 'B.Lib.Sc. (Bachelor of Library Science)', field:[]},
    {degree: 'B.Sc. (Bachelor of Science)',value: 'B.Sc. (Bachelor of Science)', field:[]},
    {degree: 'B.Tech (Bachelor of Technology)',value: 'B.Tech (Bachelor of Technology)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'B.E. (Bachelor of Engineering)',value: 'B.E. (Bachelor of Engineering)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'BCA (Bachelor of Computer Applications)',value: 'BCA (Bachelor of Computer Applications)', field:[]},
    {degree: 'B.Arch (Bachelor of Architecture)',value: 'B.Arch (Bachelor of Architecture)', field:[]},
    {degree: 'B.Plan (Bachelor of Planning)',value: 'B.Plan (Bachelor of Planning)', field:[]},
    {degree: 'BBA (Bachelor of Business Administration)',value: 'BBA (Bachelor of Business Administration)', field:[]},
    {degree: 'BBM (Bachelor of Business Management)',value: 'BBM (Bachelor of Business Management)', field:[]},
    {degree: 'BMS (Bachelor of Management Studies)',value: 'BMS (Bachelor of Management Studies)', field:[]},
    {degree: 'MBBS (Bachelor of Medicine and Bachelor of Surgery)',value: 'MBBS (Bachelor of Medicine and Bachelor of Surgery)', field:[]},
    {degree: 'BDS (Bachelor of Dental Surgery)',value: 'BDS (Bachelor of Dental Surgery)', field:[]},
    {degree: 'BPT (Bachelor of Physiotherapy)',value: 'BPT (Bachelor of Physiotherapy)', field:[]},
    {degree: 'B.Sc. Nursing',value: 'B.Sc. Nursing', field:[]},
    {degree: 'B.Pharm (Bachelor of Pharmacy)',value: 'B.Pharm (Bachelor of Pharmacy)', field:[]},
    {degree: 'BHMS (Bachelor of Homeopathy)',value: 'BHMS (Bachelor of Homeopathy)', field:[]},
    {degree: 'BAMS (Bachelor of Ayurveda, Medicine & Surgery)',value: 'BAMS (Bachelor of Ayurveda, Medicine & Surgery)', field:[]},
    {degree: 'BUMS (Bachelor of Unani Medicine & Surgery)',value: 'BUMS (Bachelor of Unani Medicine & Surgery)', field:[]},
    {degree: 'BNYS (Bachelor of Naturopathy & Yoga Science)',value: 'BNYS (Bachelor of Naturopathy & Yoga Science)', field:[]},
    {degree: 'BVSc & AH (Bachelor of Veterinary Science & Animal Husbandry)',value: 'BVSc & AH (Bachelor of Veterinary Science & Animal Husbandry)', field:[]},
    {degree: 'LL.B. (Bachelor of Laws)',value: 'LL.B. (Bachelor of Laws)', field:[]},
    {degree: 'B.Ed (Bachelor of Education)',value: 'B.Ed (Bachelor of Education)', field:[]},
    {degree: 'B.El.Ed (Bachelor of Elementary Education)',value: 'B.El.Ed (Bachelor of Elementary Education)', field:[]},
    {degree: 'BPEd (Bachelor of Physical Education)',value: 'BPEd (Bachelor of Physical Education)', field:[]},
    {degree: 'B.Des (Bachelor of Design)',value: 'B.Des (Bachelor of Design)', field:[]},
    {degree: 'BHM (Bachelor of Hotel Management)',value: 'BHM (Bachelor of Hotel Management)', field:[]},
    {degree: 'BFA (Fine Arts)',value: 'BFA (Fine Arts)', field:[]},
    {degree: 'M.A. (Master of Arts)',value: 'M.A. (Master of Arts)', field:[]},
    {degree: 'MSW (Master of Social Work)',value: 'MSW (Master of Social Work)', field:[]},
    {degree: 'M.Lib.Sc. (Library Science)',value: 'M.Lib.Sc. (Library Science)', field:[]},
    {degree: 'M.Sc. (Master of Science)',value: 'M.Sc. (Master of Science)', field:[]},
    {degree: 'M.Tech (Master of Technology)',value: 'M.Te (Master of Technology)', field:[]},
    {degree: 'M.E. (Master of Engineering)',value: 'M.E. (Master of Engineering)', field:[]},
    {degree: 'MBA (Master of Business Administration)',value: 'MBA (Master of Business Administration)', field:[]},
    {degree: 'PGDM (Post Graduate Diploma in Management)',value: 'PGDM (Post Graduate Diploma in Management)', field:[]},
    {degree: 'MD/MS (Doctor of Medicine / Master of Surgery)',value: 'MD/MS (Doctor of Medicine / Master of Surgery)', field:[]},
    {degree: 'MDS (Master of Dental Surgery)',value: 'MDS (Master of Dental Surgery)', field:[]},
    {degree: 'MCA (Master of Computer Applications)',value: 'MCA (Master of Computer Applications)', field:[]},
    {degree: 'M.Arch (Master of Architecture)',value: 'M.Arch (Master of Architecture)', field:[]},
    {degree: 'M.Com (Master of Commerce)',value: 'M.Com (Master of Commerce)', field:[]},
    {degree: 'M.Pharm (Master of Pharmacy)',value: 'M.Pharm (Master of Pharmacy)', field:[]},
    {degree: 'MPT (Master of Physiotherapy)',value: 'MPT (Master of Physiotherapy)', field:[]},
    {degree: 'M.Sc. Nursing',value: 'M.Sc. Nursing', field:[]},
    {degree: 'LL.M. (Master of Laws)',value: 'LL.M. (Master of Laws)', field:[]},
    {degree: 'M.Ed (Master of Education)',value: 'M.Ed (Master of Education)', field:[]},
    {degree: 'MPEd (Master of Physical Education)',value: 'MPEd (Master of Physical Education)', field:[]},
    {degree: 'M.Des (Master of Design)',value: 'M.Des (Master of Design)', field:[]},
    {degree: 'MHM (Master of Hotel Management)',value: 'MHM (Master of Hotel Management)', field:[]},
    {degree: 'Ph.D. (Doctor of Philosophy)',value: 'Ph.D. (Doctor of Philosophy)', field:[]},
    {degree: 'D.Sc. (Doctor of Science)',value: 'D.Sc. (Doctor of Science)', field:[]},
    {degree: 'D.Litt. (Doctor of Literature)',value: 'D.Litt. (Doctor of Literature)', field:[]},
    {degree: 'MD (Doctor of Medicine)',value: 'MD (Doctor of Medicine)', field:[]},
    {degree: 'Polytechnic Diplomas (Engineering, IT, Electronics, etc.)',value: 'Polytechnic Diplomas (Engineering, IT, Electronics, etc.)', field:[]},
    {degree: 'Diploma in Pharmacy (D.Pharm)',value: 'Diploma in Pharmacy (D.Pharm)', field:[]},
    {degree: 'Nursing Diplomas (GNM, ANM)',value: 'Nursing Diplomas (GNM, ANM)', field:[]},
    {degree: 'Teacher Training Diplomas (D.Ed, BTC)',value: 'Teacher Training Diplomas (D.Ed, BTC)', field:[]},
    {degree: 'Hotel Management Diplomas',value: 'Hotel Management Diplomas', field:[]},
    {degree: 'Short-term certifications in IT, AI, Data Science, etc.',value: 'Short-term certifications in IT, AI, Data Science, etc.', field:[]},
  ]