export const DEGREE = [
    {degree: 'B.A. (Bachelor of Arts)', value: 'B.A. (Bachelor of Arts)', field:[
      {name: 'Literature (English, Hindi, Sanskrit, Regional Languages)',value: 'Literature (English, Hindi, Sanskrit, Regional Languages)'},
      {name: 'History',value: 'History'},
      {name: 'Geography',value: 'Geography'},
      {name: 'Political Science',value: 'Political Science'},
      {name: 'Sociology',value: 'Sociology'},
      {name: 'Psychology',value: 'Psychology'},
      {name: 'Economics',value: 'Economics'},
      {name: 'Philosophy',value: 'Philosophy'},
      {name: 'Anthropology',value: 'Anthropology'},
      {name: 'Archaeology',value: 'Archaeology'},
      {name: 'Journalism & Mass Communication',value: 'Journalism & Mass Communication'},
      {name: 'Fine Arts',value: 'Fine Arts'},
      {name: 'Performing Arts',value: 'Performing Arts'},
      {name: 'Music',value: 'Music'},
      {name: 'Dance',value: 'Dance'},
      {name: 'Theatre',value: 'Theatre'},
    ]},
    {degree: 'B.S.W. (Bachelor of Social Work)', value: 'B.S.W. (Bachelor of Social Work)', field:[]},
    {degree: 'B. Com. (Bachelor of Commerce)', value: 'B. Com. (Bachelor of Commerce)', field:[
        {name: 'Accounting & Finance',value: 'Accounting & Finance'},
        {name: 'Banking & Insurance',value: 'Banking & Insurance'},
        {name: 'Auditing',value: 'Auditing'},
        {name: 'Taxation',value: 'Taxation'},
        {name: 'Economics & Business Studies',value: 'Economics & Business Studies'},
        {name: 'International Business',value: 'International Business'},
        {name: 'E-Commerce',value: 'E-Commerce'},
    ]},
    {degree: 'B.F.A. (Bachelor of Fine Arts)', value: 'B.F.A. (Bachelor of Fine Arts)', field:[
        {name: 'Visual Arts (Painting, Applied Arts, Sculpture, Printmaking)',value: 'Visual Arts (Painting, Applied Arts, Sculpture, Printmaking)'},
        {name: 'Mural Art',value: 'Mural Art'},
        {name: 'Portraiture',value: 'Portraiture'},
        {name: 'Calligraphy',value: 'Calligraphy'},
        {name: 'Design-Oriented Graphic Design, Animation & Multimedia, Photography, Illustration, Industrial Design Basics, Textile Design',
        value: 'Design-Oriented Graphic Design, Animation & Multimedia, Photography, Illustration, Industrial Design Basics, Textile Design'},
        {name: 'Performing Arts (Theatre / Acting, Music, Dance)',
        value: 'Performing Arts (Theatre / Acting, Music, Dance)'},
        {name: 'Visual Communication',value: 'Visual Communication'},
        {name: 'Digital Art & New Media',value: 'Digital Art & New Media'},
        {name: 'Art History & Art Criticism',value: 'Art History & Art Criticism'},
        {name: 'Installation Art',value: 'Installation Art'},
        {name: 'Film & Video Arts',value: 'Film & Video Arts'},
    ]},
    {degree: 'B.Lib.Sc. (Bachelor of Library Science)', value: 'B.Lib.Sc. (Bachelor of Library Science)', field:[]},
    {degree: 'B.Sc. (Bachelor of Science)',value: 'B.Sc. (Bachelor of Science)', field:[
        {name: 'Agriculture',value: 'Agriculture'},
        {name: 'Anesthesia Technology',value: 'Anesthesia Technology'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Aviation Science',value: 'Aviation Science'},
        {name: 'Biochemistry',value: 'Biochemistry'},
        {name: 'Biology',value: 'Biology'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Botany',value: 'Botany'},
        {name: 'Chemistry',value: 'Chemistry'},
        {name: 'Computer Science',value: 'Computer Science'},
        {name: 'Cybersecurity',value: 'Cybersecurity'},
        {name: 'Dairy Science',value: 'Dairy Science'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics',value: 'Electronics'},
        {name: 'Environmental Science',value: 'Environmental Science'},
        {name: 'Environmental Studies',value: 'Environmental Studies'},
        {name: 'Fashion & Apparel Science',value: 'Fashion & Apparel Science'},
        {name: 'Fisheries Science',value: 'Fisheries Science'},
        {name: 'Food Technology',value: 'Food Technology'},
        {name: 'Forensic Science',value: 'Forensic Science'},
        {name: 'Forestry',value: 'Forestry'},
        {name: 'Genetics',value: 'Genetics'},
        {name: 'Geography',value: 'Geography'},
        {name: 'Geology',value: 'Geology'},
        {name: 'Home Science',value: 'Home Science'},
        {name: 'Horticulture',value: 'Horticulture'},
        {name: 'Hospitality & Hotel Management (B.Sc. H&HA)',value: 'Hospitality & Hotel Management (B.Sc. H&HA)'},
        {name: 'Information Technology (IT)',value: 'Information Technology (IT)'},
        {name: 'Mathematics',value: 'Mathematics'},
        {name: 'Medical Laboratory Technology (MLT)',value: 'Medical Laboratory Technology (MLT)'},
        {name: 'Meteorology',value: 'Meteorology'},
        {name: 'Microbiology',value: 'Microbiology'},
        {name: 'Multimedia & Animation',value: 'Multimedia & Animation'},
        {name: 'Nursing',value: 'Nursing'},
        {name: 'Nutrition & Dietetics',value: 'Nutrition & Dietetics'},
        {name: 'Occupational Therapy',value: 'Occupational Therapy'},
        {name: 'Oceanography',value: 'Oceanography'},
        {name: 'Optometry',value: 'Optometry'},
        {name: 'Physics',value: 'Physics'},
        {name: 'Physiotherapy',value: 'Physiotherapy'},
        {name: 'Psychology',value: 'Psychology'},
        {name: 'Pure Sciences',value: 'Pure Sciences'},
        {name: 'Radiology & Imaging',value: 'Radiology & Imaging'},
        {name: 'Sericulture',value: 'Sericulture'},
        {name: 'Software Systems',value: 'Software Systems'},
        {name: 'Statistics',value: 'Statistics'},
        {name: 'Zoology',value: 'Zoology'},   
    ]},
    {degree: 'B.Tech (Bachelor of Technology)',value: 'B.Tech (Bachelor of Technology)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'B.E. (Bachelor of Engineering)',value: 'B.E. (Bachelor of Engineering)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'BCA (Bachelor of Computer Applications)',value: 'BCA (Bachelor of Computer Applications)', field:[
        {name: 'Computer Science',value: 'Computer Science'},
        {name: 'Information Technology (IT)',value: 'Information Technology (IT)'},
        {name: 'Artificial Intelligence & Machine Learning (AI & ML)',value: 'Artificial Intelligence & Machine Learning (AI & ML)'},
        {name: 'Data Science & Big Data Analytics',value: 'Data Science & Big Data Analytics'},
        {name: 'Cyber Security & Ethical Hacking',value: 'Cyber Security & Ethical Hacking'},
        {name: 'Cloud Computing',value: 'Cloud Computing'},
        {name: 'Internet of Things (IoT)',value: 'Internet of Things (IoT)'},
        {name: 'Blockchain Technology',value: 'Blockchain Technology'},
        {name: 'Augmented Reality (AR) & Virtual Reality (VR)',value: 'Augmented Reality (AR) & Virtual Reality (VR)'},
        {name: 'Game Development',value: 'Game Development'},
        {name: 'Animation & Multimedia',value: 'Animation & Multimedia'},
        {name: 'Database Management Systems (DBMS)',value: 'Database Management Systems (DBMS)'},
        {name: 'Web Development & Mobile App Development',value: 'Web Development & Mobile App Development'},
        {name: 'Software Engineering',value: 'Software Engineering'},
        {name: 'Networking & Security',value: 'Networking & Security'},
        {name: 'Financial Technology (FinTech)',value: 'Financial Technology (FinTech)'},
    ]},
    {degree: 'B.Arch (Bachelor of Architecture)',value: 'B.Arch (Bachelor of Architecture)', field:[
        { name: 'Architectural Design', value: 'Architectural Design' },
        { name: 'Building Construction & Materials', value: 'Building Construction & Materials' },
        { name: 'Building Services (HVAC, Lighting, Acoustics, Electrical, Plumbing)', value: 'Building Services (HVAC, Lighting, Acoustics, Electrical, Plumbing)' },
        { name: 'Computer-Aided Design (AutoCAD, Revit, BIM, 3D Modeling, Parametric Design)', value: 'Computer-Aided Design (AutoCAD, Revit, BIM, 3D Modeling, Parametric Design)' },
        { name: 'Construction Project Management', value: 'Construction Project Management' },
        { name: 'Environmental Studies (Climate-responsive design, Sustainability, Green Buildings)', value: 'Environmental Studies (Climate-responsive design, Sustainability, Green Buildings)' },
        { name: 'History of Architecture', value: 'History of Architecture' },
        { name: 'Interior Design & Space Planning', value: 'Interior Design & Space Planning' },
        { name: 'Landscape Architecture', value: 'Landscape Architecture' },
        { name: 'Professional Practice & Ethics', value: 'Professional Practice & Ethics' },
        { name: 'Structural Engineering for Architects', value: 'Structural Engineering for Architects' },
        { name: 'Theory of Architecture', value: 'Theory of Architecture' },
        { name: 'Town & Regional Planning', value: 'Town & Regional Planning' },
        { name: 'Urban Planning & Design', value: 'Urban Planning & Design' }
    ]},
    {degree: 'B.Plan (Bachelor of Planning)',value: 'B.Plan (Bachelor of Planning)', field:[
        { name: 'Environmental Planning', value: 'Environmental Planning' },
        { name: 'GIS & Remote Sensing Applications in Planning', value: 'GIS & Remote Sensing Applications in Planning' },
        { name: 'Housing & Community Planning', value: 'Housing & Community Planning' },
        { name: 'Infrastructure Planning', value: 'Infrastructure Planning' },
        { name: 'Regional Planning', value: 'Regional Planning' },
        { name: 'Rural Planning', value: 'Rural Planning' },
        { name: 'Sustainable Development & Smart Cities', value: 'Sustainable Development & Smart Cities' },
        { name: 'Transport Planning', value: 'Transport Planning' },
        { name: 'Urban Design & Landscape Planning', value: 'Urban Design & Landscape Planning' },
        { name: 'Urban Planning', value: 'Urban Planning' }
    ]},
    {degree: 'BBA (Bachelor of Business Administration)',value: 'BBA (Bachelor of Business Administration)', field:[
        { name: 'Business Analytics', value: 'Business Analytics' },
        { name: 'Digital Marketing / E-Commerce', value: 'Digital Marketing / E-Commerce' },
        { name: 'Entrepreneurship / Family Business', value: 'Entrepreneurship / Family Business' },
        { name: 'Event Management', value: 'Event Management' },
        { name: 'Finance', value: 'Finance' },
        { name: 'Healthcare Management / Hospital Administration', value: 'Healthcare Management / Hospital Administration' },
        { name: 'Hospitality & Hotel Management', value: 'Hospitality & Hotel Management' },
        { name: 'Human Resource Management (HRM)', value: 'Human Resource Management (HRM)' },
        { name: 'Information Technology (IT)', value: 'Information Technology (IT)' },
        { name: 'International Business', value: 'International Business' },
        { name: 'Marketing', value: 'Marketing' },
        { name: 'Operations Management', value: 'Operations Management' },
        { name: 'Real Estate & Urban Infrastructure', value: 'Real Estate & Urban Infrastructure' },
        { name: 'Retail Management', value: 'Retail Management' },
        { name: 'Sports Management', value: 'Sports Management' },
        { name: 'Supply Chain & Logistics', value: 'Supply Chain & Logistics' },
        { name: 'Tourism & Travel Management', value: 'Tourism & Travel Management' }
    ]},
    {degree: 'BBM (Bachelor of Business Management)',value: 'BBM (Bachelor of Business Management)', field:[
        { name: 'Banking & Insurance', value: 'Banking & Insurance' },
        { name: 'Business Analytics', value: 'Business Analytics' },
        { name: 'Entrepreneurship & Startups', value: 'Entrepreneurship & Startups' },
        { name: 'Finance', value: 'Finance' },
        { name: 'Healthcare Management', value: 'Healthcare Management' },
        { name: 'Hospitality & Tourism Management', value: 'Hospitality & Tourism Management' },
        { name: 'Human Resource Management (HRM)', value: 'Human Resource Management (HRM)' },
        { name: 'Information Technology (IT) Management', value: 'Information Technology (IT) Management' },
        { name: 'International Business', value: 'International Business' },
        { name: 'Marketing', value: 'Marketing' },
        { name: 'Operations & Supply Chain Management', value: 'Operations & Supply Chain Management' },
        { name: 'Retail & E-Commerce Management', value: 'Retail & E-Commerce Management' }
    ]},
    {degree: 'BMS (Bachelor of Management Studies)',value: 'BMS (Bachelor of Management Studies)', field:[
        { name: 'Business Analytics', value: 'Business Analytics' },
        { name: 'Digital Marketing', value: 'Digital Marketing' },
        { name: 'Entrepreneurship & Innovation', value: 'Entrepreneurship & Innovation' },
        { name: 'Finance', value: 'Finance' },
        { name: 'Human Resource Management (HRM)', value: 'Human Resource Management (HRM)' },
        { name: 'International Business', value: 'International Business' },
        { name: 'Management Consulting', value: 'Management Consulting' },
        { name: 'Marketing', value: 'Marketing' },
        { name: 'Operations Management', value: 'Operations Management' },
        { name: 'Retail & E-Commerce', value: 'Retail & E-Commerce' },
        { name: 'Supply Chain & Logistics', value: 'Supply Chain & Logistics' }
    ]},
    {degree: 'MBBS (Bachelor of Medicine and Bachelor of Surgery)',value: 'MBBS (Bachelor of Medicine and Bachelor of Surgery)', field:[
        { name: 'Anatomy', value: 'Anatomy' },
        { name: 'Anesthesiology', value: 'Anesthesiology' },
        { name: 'Biochemistry', value: 'Biochemistry' },
        { name: 'Community Medicine (PSM – Preventive & Social Medicine)', value: 'Community Medicine (PSM – Preventive & Social Medicine)' },
        { name: 'Dentistry (basic exposure)', value: 'Dentistry (basic exposure)' },
        { name: 'Dermatology (Skin & Venereal Diseases)', value: 'Dermatology (Skin & Venereal Diseases)' },
        { name: 'Emergency Medicine', value: 'Emergency Medicine' },
        { name: 'Forensic Medicine & Toxicology', value: 'Forensic Medicine & Toxicology' },
        { name: 'General Medicine', value: 'General Medicine' },
        { name: 'General Surgery', value: 'General Surgery' },
        { name: 'Microbiology', value: 'Microbiology' },
        { name: 'Obstetrics & Gynecology', value: 'Obstetrics & Gynecology' },
        { name: 'Ophthalmology (Eye)', value: 'Ophthalmology (Eye)' },
        { name: 'Orthopedics', value: 'Orthopedics' },
        { name: 'Otorhinolaryngology (ENT – Ear, Nose, Throat)', value: 'Otorhinolaryngology (ENT – Ear, Nose, Throat)' },
        { name: 'Pathology', value: 'Pathology' },
        { name: 'Pediatrics', value: 'Pediatrics' },
        { name: 'Pharmacology', value: 'Pharmacology' },
        { name: 'Physiology', value: 'Physiology' },
        { name: 'Psychiatry', value: 'Psychiatry' },
        { name: 'Radiology', value: 'Radiology' }
    ]},
    {degree: 'BDS (Bachelor of Dental Surgery)',value: 'BDS (Bachelor of Dental Surgery)', field:[
        { name: 'Conservative Dentistry & Endodontics', value: 'Conservative Dentistry & Endodontics' },
        { name: 'Oral & Maxillofacial Surgery', value: 'Oral & Maxillofacial Surgery' },
        { name: 'Oral Medicine & Radiology', value: 'Oral Medicine & Radiology' },
        { name: 'Oral Pathology & Microbiology', value: 'Oral Pathology & Microbiology' },
        { name: 'Orthodontics & Dentofacial Orthopaedics', value: 'Orthodontics & Dentofacial Orthopaedics' },
        { name: 'Pedodontics & Preventive Dentistry', value: 'Pedodontics & Preventive Dentistry' },
        { name: 'Periodontology', value: 'Periodontology' },
        { name: 'Prosthodontics & Crown & Bridge', value: 'Prosthodontics & Crown & Bridge' },
        { name: 'Public Health Dentistry (Community Dentistry)', value: 'Public Health Dentistry (Community Dentistry)' }
    ]},
    {degree: 'BPT (Bachelor of Physiotherapy)',value: 'BPT (Bachelor of Physiotherapy)', field:[
        { name: 'Cardiopulmonary / Cardiothoracic Physiotherapy', value: 'Cardiopulmonary / Cardiothoracic Physiotherapy' },
        { name: 'Community-Based Physiotherapy', value: 'Community-Based Physiotherapy' },
        { name: 'Geriatric Physiotherapy', value: 'Geriatric Physiotherapy' },
        { name: 'Hand Rehabilitation', value: 'Hand Rehabilitation' },
        { name: 'Neurological Physiotherapy', value: 'Neurological Physiotherapy' },
        { name: 'Oncology Physiotherapy', value: 'Oncology Physiotherapy' },
        { name: 'Orthopedic / Musculoskeletal Physiotherapy', value: 'Orthopedic / Musculoskeletal Physiotherapy' },
        { name: 'Pediatric Physiotherapy', value: 'Pediatric Physiotherapy' },
        { name: 'Sports Physiotherapy', value: 'Sports Physiotherapy' },
        { name: 'Women’s Health / Obstetric Physiotherapy', value: 'Women’s Health / Obstetric Physiotherapy' }
    ]},
    {degree: 'B.Pharm (Bachelor of Pharmacy)',value: 'B.Pharm (Bachelor of Pharmacy)', field:[
        { name: 'Hospital & Clinical Pharmacy', value: 'Hospital & Clinical Pharmacy' },
        { name: 'Pharmaceutical Analysis', value: 'Pharmaceutical Analysis' },
        { name: 'Pharmaceutical Biotechnology', value: 'Pharmaceutical Biotechnology' },
        { name: 'Pharmaceutical Chemistry', value: 'Pharmaceutical Chemistry' },
        { name: 'Pharmaceutics', value: 'Pharmaceutics' },
        { name: 'Pharmacognosy', value: 'Pharmacognosy' },
        { name: 'Pharmacology', value: 'Pharmacology' },
        { name: 'Regulatory Affairs & Pharmaceutical Jurisprudence', value: 'Regulatory Affairs & Pharmaceutical Jurisprudence' }
    ]},
    {degree: 'BHMS (Bachelor of Homeopathy)',value: 'BHMS (Bachelor of Homeopathy)', field:[
        { name: 'Anatomy', value: 'Anatomy' },
        { name: 'Community Medicine', value: 'Community Medicine' },
        { name: 'Forensic Medicine & Toxicology', value: 'Forensic Medicine & Toxicology' },
        { name: 'Homeopathic Materia Medica', value: 'Homeopathic Materia Medica' },
        { name: 'Homeopathic Pharmacy', value: 'Homeopathic Pharmacy' },
        { name: 'Obstetrics & Gynaecology', value: 'Obstetrics & Gynaecology' },
        { name: 'Organon of Medicine, Principles of Homeopathic Philosophy & Psychology', value: 'Organon of Medicine, Principles of Homeopathic Philosophy & Psychology' },
        { name: 'Pathology & Microbiology', value: 'Pathology & Microbiology' },
        { name: 'Physiology including Biochemistry', value: 'Physiology including Biochemistry' },
        { name: 'Practice of Medicine', value: 'Practice of Medicine' },
        { name: 'Repertory', value: 'Repertory' },
        { name: 'Surgery', value: 'Surgery' }
    ]},
    {degree: 'BAMS (Bachelor of Ayurveda, Medicine & Surgery)',value: 'BAMS (Bachelor of Ayurveda, Medicine & Surgery)', field:[
        { name: 'Agad Tantra, Vyavahar Ayurveda & Vidhi Vaidyaka (Toxicology, Forensic Medicine, Medical Jurisprudence)', value: 'Agad Tantra, Vyavahar Ayurveda & Vidhi Vaidyaka (Toxicology, Forensic Medicine, Medical Jurisprudence)' },
        { name: 'Dravyaguna Vigyan (Ayurvedic Pharmacology & Materia Medica)', value: 'Dravyaguna Vigyan (Ayurvedic Pharmacology & Materia Medica)' },
        { name: 'Kaumarbhritya / Bala Roga (Pediatrics)', value: 'Kaumarbhritya / Bala Roga (Pediatrics)' },
        { name: 'Kayachikitsa (General Medicine)', value: 'Kayachikitsa (General Medicine)' },
        { name: 'Kriya Sharir (Physiology)', value: 'Kriya Sharir (Physiology)' },
        { name: 'Panchakarma (Detoxification & Rejuvenation Therapies)', value: 'Panchakarma (Detoxification & Rejuvenation Therapies)' },
        { name: 'Prasuti Tantra & Stri Roga (Obstetrics & Gynaecology)', value: 'Prasuti Tantra & Stri Roga (Obstetrics & Gynaecology)' },
        { name: 'Rachana Sharir (Anatomy)', value: 'Rachana Sharir (Anatomy)' },
        { name: 'Rasashastra & Bhaishajya Kalpana (Ayurvedic Pharmaceutics & Toxicology)', value: 'Rasashastra & Bhaishajya Kalpana (Ayurvedic Pharmaceutics & Toxicology)' },
        { name: 'Roga Nidan & Vikriti Vigyan (Pathology & Diagnostics)', value: 'Roga Nidan & Vikriti Vigyan (Pathology & Diagnostics)' },
        { name: 'Samhita & Siddhanta (Ayurvedic philosophy, classical texts)', value: 'Samhita & Siddhanta (Ayurvedic philosophy, classical texts)' },
        { name: 'Shalakya Tantra (ENT, Ophthalmology, Dentistry, Head & Neck diseases)', value: 'Shalakya Tantra (ENT, Ophthalmology, Dentistry, Head & Neck diseases)' },
        { name: 'Shalya Tantra (Surgery including Para-Surgical Techniques like Kshar Sutra)', value: 'Shalya Tantra (Surgery including Para-Surgical Techniques like Kshar Sutra)' },
        { name: 'Swasthavritta & Yoga (Preventive & Social Medicine, Yoga)', value: 'Swasthavritta & Yoga (Preventive & Social Medicine, Yoga)' }
    ]},
    {degree: 'BUMS (Bachelor of Unani Medicine & Surgery)',value: 'BUMS (Bachelor of Unani Medicine & Surgery)', field:[
        { name: 'Amraze Jild wa Tazeeniyat (Dermatology & Cosmetology)', value: 'Amraze Jild wa Tazeeniyat (Dermatology & Cosmetology)' },
        { name: 'Ilmul Advia (Pharmacology & Pharmacy)', value: 'Ilmul Advia (Pharmacology & Pharmacy)' },
        { name: 'Ilmul Amraz (Pathology)', value: 'Ilmul Amraz (Pathology)' },
        { name: 'Ilmul Amraz-e-Asab (Neurology)', value: 'Ilmul Amraz-e-Asab (Neurology)' },
        { name: 'Ilmul Amraz-e-Qalb (Cardiology)', value: 'Ilmul Amraz-e-Qalb (Cardiology)' },
        { name: 'Ilmul Amraze Ain, Uzn, Anaf, Halaq (Ophthalmology & ENT)', value: 'Ilmul Amraze Ain, Uzn, Anaf, Halaq (Ophthalmology & ENT)' },
        { name: 'Ilmul Asriya (Modern Medicine)', value: 'Ilmul Asriya (Modern Medicine)' },
        { name: 'Ilmul Atfal (Pediatrics)', value: 'Ilmul Atfal (Pediatrics)' },
        { name: 'Ilmul Jarahat (Surgery)', value: 'Ilmul Jarahat (Surgery)' },
        { name: 'Ilmul Qabalat wa Niswan (Obstetrics & Gynaecology)', value: 'Ilmul Qabalat wa Niswan (Obstetrics & Gynaecology)' },
        { name: 'Ilmul Saidla (Pharmaceutical Science / Pharmacy)', value: 'Ilmul Saidla (Pharmaceutical Science / Pharmacy)' },
        { name: 'Ilmul Tashreeh (Anatomy)', value: 'Ilmul Tashreeh (Anatomy)' },
        { name: 'Mahiyat-ul-Amraz (Pathology & Microbiology)', value: 'Mahiyat-ul-Amraz (Pathology & Microbiology)' },
        { name: 'Moalijat (Medicine)', value: 'Moalijat (Medicine)' },
        { name: 'Tahaffuzi wa Samaji Tib (Preventive & Social Medicine / Community Medicine)', value: 'Tahaffuzi wa Samaji Tib (Preventive & Social Medicine / Community Medicine)' }
    ]},
    {degree: 'BNYS (Bachelor of Naturopathy & Yoga Science)',value: 'BNYS (Bachelor of Naturopathy & Yoga Science)', field:[
        { name: 'Acupuncture & Acupressure', value: 'Acupuncture & Acupressure' },
        { name: 'Anatomy', value: 'Anatomy' },
        { name: 'Biochemistry', value: 'Biochemistry' },
        { name: 'Chromotherapy', value: 'Chromotherapy' },
        { name: 'Community Medicine / Public Health', value: 'Community Medicine / Public Health' },
        { name: 'Fasting Therapy', value: 'Fasting Therapy' },
        { name: 'Forensic Medicine & Toxicology', value: 'Forensic Medicine & Toxicology' },
        { name: 'Hydrotherapy', value: 'Hydrotherapy' },
        { name: 'Magnetotherapy', value: 'Magnetotherapy' },
        { name: 'Manipulative Therapy (Massage, Chiropractic, Osteopathy basics)', value: 'Manipulative Therapy (Massage, Chiropractic, Osteopathy basics)' },
        { name: 'Mud Therapy', value: 'Mud Therapy' },
        { name: 'Naturopathy Medicine', value: 'Naturopathy Medicine' },
        { name: 'Nutrition & Dietetics', value: 'Nutrition & Dietetics' },
        { name: 'Pathology & Microbiology', value: 'Pathology & Microbiology' },
        { name: 'Physical Medicine & Rehabilitation', value: 'Physical Medicine & Rehabilitation' },
        { name: 'Physiology', value: 'Physiology' },
        { name: 'Psychology & Psychiatry', value: 'Psychology & Psychiatry' },
        { name: 'Research Methodology & Statistics', value: 'Research Methodology & Statistics' },
        { name: 'Yoga Therapy', value: 'Yoga Therapy' }
    ]},
    {degree: 'BVSc & AH (Bachelor of Veterinary Science & Animal Husbandry)',value: 'BVSc & AH (Bachelor of Veterinary Science & Animal Husbandry)', field:[
        { name: 'Anatomy – Veterinary Anatomy, Histology, Embryology', value: 'Anatomy – Veterinary Anatomy, Histology, Embryology' },
        { name: 'Animal Genetics & Breeding – Population Genetics, Molecular Genetics, Animal Improvement', value: 'Animal Genetics & Breeding – Population Genetics, Molecular Genetics, Animal Improvement' },
        { name: 'Animal Nutrition – Feed Science, Applied Nutrition, Clinical Nutrition', value: 'Animal Nutrition – Feed Science, Applied Nutrition, Clinical Nutrition' },
        { name: 'Extension Education – Veterinary Extension, Rural Development, Communication Technology', value: 'Extension Education – Veterinary Extension, Rural Development, Communication Technology' },
        { name: 'Gynaecology & Obstetrics – Reproductive Physiology, Animal Breeding, Assisted Reproduction', value: 'Gynaecology & Obstetrics – Reproductive Physiology, Animal Breeding, Assisted Reproduction' },
        { name: 'Livestock Production & Management (LPM) – Dairy Production, Poultry Production, Sheep & Goat Farming, Pig Farming, Equine Management, Camelid Management', value: 'Livestock Production & Management (LPM) – Dairy Production, Poultry Production, Sheep & Goat Farming, Pig Farming, Equine Management, Camelid Management' },
        { name: 'Livestock Products Technology (LPT) – Meat Science, Milk & Dairy Technology, By-products', value: 'Livestock Products Technology (LPT) – Meat Science, Milk & Dairy Technology, By-products' },
        { name: 'Medicine – Veterinary Medicine, Preventive Medicine, Clinical Medicine', value: 'Medicine – Veterinary Medicine, Preventive Medicine, Clinical Medicine' },
        { name: 'Microbiology – Veterinary Microbiology, Immunology, Virology, Bacteriology, Mycology', value: 'Microbiology – Veterinary Microbiology, Immunology, Virology, Bacteriology, Mycology' },
        { name: 'Parasitology – Veterinary Parasitology, Helminthology, Protozoology, Entomology', value: 'Parasitology – Veterinary Parasitology, Helminthology, Protozoology, Entomology' },
        { name: 'Pathology – Veterinary Pathology, Clinical Pathology, Histopathology', value: 'Pathology – Veterinary Pathology, Clinical Pathology, Histopathology' },
        { name: 'Pharmacology & Toxicology – Veterinary Pharmacology, Veterinary Toxicology', value: 'Pharmacology & Toxicology – Veterinary Pharmacology, Veterinary Toxicology' },
        { name: 'Physiology & Biochemistry – Veterinary Physiology, Veterinary Biochemistry', value: 'Physiology & Biochemistry – Veterinary Physiology, Veterinary Biochemistry' },
        { name: 'Public Health & Epidemiology – Veterinary Public Health, Zoonoses, Food Safety, Epidemiology', value: 'Public Health & Epidemiology – Veterinary Public Health, Zoonoses, Food Safety, Epidemiology' },
        { name: 'Surgery & Radiology – Veterinary Surgery, Anaesthesiology, Radiology, Diagnostic Imaging', value: 'Surgery & Radiology – Veterinary Surgery, Anaesthesiology, Radiology, Diagnostic Imaging' }
    ]},
    {degree: 'LL.B. (Bachelor of Laws)',value: 'LL.B. (Bachelor of Laws)', field:[]},
    {degree: 'B.Ed (Bachelor of Education)',value: 'B.Ed (Bachelor of Education)', field:[
        { name: 'Biology', value: 'Biology' },
        { name: 'Chemistry', value: 'Chemistry' },
        { name: 'Commerce', value: 'Commerce' },
        { name: 'Computer Science', value: 'Computer Science' },
        { name: 'Economics', value: 'Economics' },
        { name: 'English', value: 'English' },
        { name: 'Fine Arts', value: 'Fine Arts' },
        { name: 'Geography', value: 'Geography' },
        { name: 'Hindi', value: 'Hindi' },
        { name: 'History', value: 'History' },
        { name: 'Home Science', value: 'Home Science' },
        { name: 'Languages', value: 'Languages' },
        { name: 'Mathematics', value: 'Mathematics' },
        { name: 'Music Education', value: 'Music Education' },
        { name: 'Physical Education', value: 'Physical Education' },
        { name: 'Physics', value: 'Physics' },
        { name: 'Political Science', value: 'Political Science' },
        { name: 'Sanskrit', value: 'Sanskrit' },
        { name: 'Special Education', value: 'Special Education' }
    ]},
    {degree: 'B.El.Ed (Bachelor of Elementary Education)',value: 'B.El.Ed (Bachelor of Elementary Education)', field:[]},
    {degree: 'BPEd (Bachelor of Physical Education)',value: 'BPEd (Bachelor of Physical Education)', field:[]},
    {degree: 'B.Des (Bachelor of Design)',value: 'B.Des (Bachelor of Design)', field:[
        { name: 'Accessory / Jewellery Design', value: 'Accessory / Jewellery Design' },
        { name: 'Animation Film Design', value: 'Animation Film Design' },
        { name: 'Apparel Design', value: 'Apparel Design' },
        { name: 'Ceramic & Glass Design', value: 'Ceramic & Glass Design' },
        { name: 'Communication Design', value: 'Communication Design' },
        { name: 'Digital Game Design', value: 'Digital Game Design' },
        { name: 'Exhibition Design', value: 'Exhibition Design' },
        { name: 'Fashion Communication', value: 'Fashion Communication' },
        { name: 'Fashion Design', value: 'Fashion Design' },
        { name: 'Film & Video Communication', value: 'Film & Video Communication' },
        { name: 'Graphic Design', value: 'Graphic Design' },
        { name: 'Industrial Design', value: 'Industrial Design' },
        { name: 'Interaction Design / UX Design', value: 'Interaction Design / UX Design' },
        { name: 'Interior & Furniture Design', value: 'Interior & Furniture Design' },
        { name: 'Product Design', value: 'Product Design' },
        { name: 'Strategic Design Management', value: 'Strategic Design Management' },
        { name: 'Textile Design', value: 'Textile Design' },
        { name: 'Toy & Game Design', value: 'Toy & Game Design' },
        { name: 'Transportation & Automobile Design', value: 'Transportation & Automobile Design' }
    ]},
    {degree: 'BHM (Bachelor of Hotel Management)',value: 'BHM (Bachelor of Hotel Management)', field:[
        { name: 'Entrepreneurship in Hospitality', value: 'Entrepreneurship in Hospitality' },
        { name: 'Event Management', value: 'Event Management' },
        { name: 'Food & Beverage Service', value: 'Food & Beverage Service' },
        { name: 'Food Production (Culinary Arts / Kitchen Operations)', value: 'Food Production (Culinary Arts / Kitchen Operations)' },
        { name: 'Front Office Operations', value: 'Front Office Operations' },
        { name: 'Hospital Operations Management', value: 'Hospital Operations Management' },
        { name: 'Hospitality Accounting & Finance', value: 'Hospitality Accounting & Finance' },
        { name: 'Hospitality Information Systems (MIS/IT in Hospitality)', value: 'Hospitality Information Systems (MIS/IT in Hospitality)' },
        { name: 'Hospitality Law & Ethics', value: 'Hospitality Law & Ethics' },
        { name: 'Hospitality Marketing & Sales', value: 'Hospitality Marketing & Sales' },
        { name: 'Housekeeping Operations', value: 'Housekeeping Operations' },
        { name: 'Human Resource Management in Hospitality', value: 'Human Resource Management in Hospitality' },
        { name: 'Resort & Club Management', value: 'Resort & Club Management' },
        { name: 'Travel & Tourism Management', value: 'Travel & Tourism Management' }
    ]},
    {degree: 'BFA (Fine Arts)',value: 'BFA (Fine Arts)', field:[
        { name: 'Applied Arts / Visual Communication', value: 'Applied Arts / Visual Communication' },
        { name: 'Art History', value: 'Art History' },
        { name: 'Dance (Classical, Contemporary, etc.)', value: 'Dance (Classical, Contemporary, etc.)' },
        { name: 'Digital Arts / Animation / New Media', value: 'Digital Arts / Animation / New Media' },
        { name: 'Film Making / Film Studies', value: 'Film Making / Film Studies' },
        { name: 'Music (Vocal, Instrumental)', value: 'Music (Vocal, Instrumental)' },
        { name: 'Painting', value: 'Painting' },
        { name: 'Photography', value: 'Photography' },
        { name: 'Printmaking', value: 'Printmaking' },
        { name: 'Sculpture', value: 'Sculpture' },
        { name: 'Textile Design / Fashion Design', value: 'Textile Design / Fashion Design' },
        { name: 'Theatre / Drama', value: 'Theatre / Drama' }
    ]},
    {degree: 'M.A. (Master of Arts)',value: 'M.A. (Master of Arts)', field:[
        {name: 'Literature (English, Hindi, Sanskrit, Regional Languages)',value: 'Literature (English, Hindi, Sanskrit, Regional Languages)'},
        {name: 'History',value: 'History'},
        {name: 'Geography',value: 'Geography'},
        {name: 'Political Science',value: 'Political Science'},
        {name: 'Sociology',value: 'Sociology'},
        {name: 'Psychology',value: 'Psychology'},
        {name: 'Economics',value: 'Economics'},
        {name: 'Philosophy',value: 'Philosophy'},
        {name: 'Anthropology',value: 'Anthropology'},
        {name: 'Archaeology',value: 'Archaeology'},
        {name: 'Journalism & Mass Communication',value: 'Journalism & Mass Communication'},
        {name: 'Fine Arts',value: 'Fine Arts'},
        {name: 'Performing Arts',value: 'Performing Arts'},
        {name: 'Music',value: 'Music'},
        {name: 'Dance',value: 'Dance'},
        {name: 'Theatre',value: 'Theatre'},
    ]},
    {degree: 'MSW (Master of Social Work)',value: 'MSW (Master of Social Work)', field:[]},
    {degree: 'M.Lib.Sc. (Library Science)',value: 'M.Lib.Sc. (Library Science)', field:[]},
    {degree: 'M.Sc. (Master of Science)',value: 'M.Sc. (Master of Science)', field:[
        {name: 'Agriculture',value: 'Agriculture'},
        {name: 'Anesthesia Technology',value: 'Anesthesia Technology'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Aviation Science',value: 'Aviation Science'},
        {name: 'Biochemistry',value: 'Biochemistry'},
        {name: 'Biology',value: 'Biology'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Botany',value: 'Botany'},
        {name: 'Chemistry',value: 'Chemistry'},
        {name: 'Computer Science',value: 'Computer Science'},
        {name: 'Cybersecurity',value: 'Cybersecurity'},
        {name: 'Dairy Science',value: 'Dairy Science'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics',value: 'Electronics'},
        {name: 'Environmental Science',value: 'Environmental Science'},
        {name: 'Environmental Studies',value: 'Environmental Studies'},
        {name: 'Fashion & Apparel Science',value: 'Fashion & Apparel Science'},
        {name: 'Fisheries Science',value: 'Fisheries Science'},
        {name: 'Food Technology',value: 'Food Technology'},
        {name: 'Forensic Science',value: 'Forensic Science'},
        {name: 'Forestry',value: 'Forestry'},
        {name: 'Genetics',value: 'Genetics'},
        {name: 'Geography',value: 'Geography'},
        {name: 'Geology',value: 'Geology'},
        {name: 'Home Science',value: 'Home Science'},
        {name: 'Horticulture',value: 'Horticulture'},
        {name: 'Hospitality & Hotel Management (B.Sc. H&HA)',value: 'Hospitality & Hotel Management (B.Sc. H&HA)'},
        {name: 'Information Technology (IT)',value: 'Information Technology (IT)'},
        {name: 'Mathematics',value: 'Mathematics'},
        {name: 'Medical Laboratory Technology (MLT)',value: 'Medical Laboratory Technology (MLT)'},
        {name: 'Meteorology',value: 'Meteorology'},
        {name: 'Microbiology',value: 'Microbiology'},
        {name: 'Multimedia & Animation',value: 'Multimedia & Animation'},
        {name: 'Nursing',value: 'Nursing'},
        {name: 'Nutrition & Dietetics',value: 'Nutrition & Dietetics'},
        {name: 'Occupational Therapy',value: 'Occupational Therapy'},
        {name: 'Oceanography',value: 'Oceanography'},
        {name: 'Optometry',value: 'Optometry'},
        {name: 'Physics',value: 'Physics'},
        {name: 'Physiotherapy',value: 'Physiotherapy'},
        {name: 'Psychology',value: 'Psychology'},
        {name: 'Pure Sciences',value: 'Pure Sciences'},
        {name: 'Radiology & Imaging',value: 'Radiology & Imaging'},
        {name: 'Sericulture',value: 'Sericulture'},
        {name: 'Software Systems',value: 'Software Systems'},
        {name: 'Statistics',value: 'Statistics'},
        {name: 'Zoology',value: 'Zoology'},   
    ]},
    {degree: 'M.Tech (Master of Technology)',value: 'M.Te (Master of Technology)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'M.E. (Master of Engineering)',value: 'M.E. (Master of Engineering)', field:[
        {name: 'Computer Science Engineering (CSE)',value: 'Computer Science Engineering (CSE)'},
        {name: 'Artificial Intelligence',value: 'Artificial Intelligence'},
        {name: 'Data Science',value: 'Data Science'},
        {name: 'Electronics & Communication',value: 'Electronics & Communication'},
        {name: 'Electrical & Electronics',value: 'Electrical & Electronics'},
        {name: 'Mechanical',value: 'Mechanical'},        
        {name: 'Civil',value: 'Civil'},
        {name: 'Chemical',value: 'Chemical'},
        {name: 'Aerospace',value: 'Aerospace'},
        {name: 'Automobile',value: 'Automobile'},
        {name: 'Mechatronics',value: 'Mechatronics'},
        {name: 'Robotics',value: 'Robotics'},
        {name: 'Marine Engineering',value: 'Marine Engineering'},
        {name: 'Metallurgy',value: 'Metallurgy'},
        {name: 'Mining',value: 'Mining'},
        {name: 'Petroleum',value: 'Petroleum'},
        {name: 'Textile',value: 'Textile'},
        {name: 'Ceramic',value: 'Ceramic'},
        {name: 'Biotechnology',value: 'Biotechnology'},
        {name: 'Bioinformatics',value: 'Bioinformatics'},
        {name: 'Biomedical Engineering',value: 'Biomedical Engineering'},
    ]},
    {degree: 'MBA (Master of Business Administration)',value: 'MBA (Master of Business Administration)', field:[
        { name: 'Agri-Business Management', value: 'Agri-Business Management' },
        { name: 'Banking & Financial Services', value: 'Banking & Financial Services' },
        { name: 'Business Analytics', value: 'Business Analytics' },
        { name: 'Digital Marketing', value: 'Digital Marketing' },
        { name: 'Entrepreneurship', value: 'Entrepreneurship' },
        { name: 'Event Management', value: 'Event Management' },
        { name: 'Finance', value: 'Finance' },
        { name: 'Healthcare & Hospital Management', value: 'Healthcare & Hospital Management' },
        { name: 'Hospitality & Tourism Management', value: 'Hospitality & Tourism Management' },
        { name: 'Human Resource Management (HRM)', value: 'Human Resource Management (HRM)' },
        { name: 'Information Technology (IT)', value: 'Information Technology (IT)' },
        { name: 'International Business', value: 'International Business' },
        { name: 'Marketing', value: 'Marketing' },
        { name: 'Operations Management', value: 'Operations Management' },
        { name: 'Project Management', value: 'Project Management' },
        { name: 'Public Policy & Management', value: 'Public Policy & Management' },
        { name: 'Retail Management', value: 'Retail Management' },
        { name: 'Rural Management', value: 'Rural Management' },
        { name: 'Sports Management', value: 'Sports Management' },
        { name: 'Strategy & Consulting', value: 'Strategy & Consulting' },
        { name: 'Supply Chain Management', value: 'Supply Chain Management' },
        { name: 'Telecom Management', value: 'Telecom Management' }
    ]},
    {degree: 'PGDM (Post Graduate Diploma in Management)',value: 'PGDM (Post Graduate Diploma in Management)', field:[
        { name: 'Banking, Financial Services & Insurance (BFSI)', value: 'Banking, Financial Services & Insurance (BFSI)' },
        { name: 'Entrepreneurship & Startups', value: 'Entrepreneurship & Startups' },
        { name: 'Finance', value: 'Finance' },
        { name: 'Healthcare & Hospital Management', value: 'Healthcare & Hospital Management' },
        { name: 'Human Resource Management (HRM)', value: 'Human Resource Management (HRM)' },
        { name: 'Information Technology (IT) / Business Analytics', value: 'Information Technology (IT) / Business Analytics' },
        { name: 'International Business (IB)', value: 'International Business (IB)' },
        { name: 'Logistics & Supply Chain', value: 'Logistics & Supply Chain' },
        { name: 'Marketing', value: 'Marketing' },
        { name: 'Media & Communication', value: 'Media & Communication' },
        { name: 'Operations & Supply Chain Management', value: 'Operations & Supply Chain Management' },
        { name: 'Retail Management', value: 'Retail Management' },
        { name: 'Rural & Agri-Business Management', value: 'Rural & Agri-Business Management' },
        { name: 'Sports Management', value: 'Sports Management' }
    ]},
    {degree: 'MD (Doctor of Medicine)',value: 'MD (Doctor of Medicine)', field:[
        { name: 'Anatomy', value: 'Anatomy' },
        { name: 'Anesthesiology', value: 'Anesthesiology' },
        { name: 'Biochemistry', value: 'Biochemistry' },
        { name: 'Community Medicine / Preventive & Social Medicine', value: 'Community Medicine / Preventive & Social Medicine' },
        { name: 'Dermatology, Venereology & Leprology (Skin & VD)', value: 'Dermatology, Venereology & Leprology (Skin & VD)' },
        { name: 'Emergency Medicine', value: 'Emergency Medicine' },
        { name: 'Forensic Medicine', value: 'Forensic Medicine' },
        { name: 'General Medicine', value: 'General Medicine' },
        { name: 'Geriatrics', value: 'Geriatrics' },
        { name: 'Microbiology', value: 'Microbiology' },
        { name: 'Nuclear Medicine', value: 'Nuclear Medicine' },
        { name: 'Pathology', value: 'Pathology' },
        { name: 'Pediatrics', value: 'Pediatrics' },
        { name: 'Pharmacology', value: 'Pharmacology' },
        { name: 'Physiology', value: 'Physiology' },
        { name: 'Psychiatry', value: 'Psychiatry' },
        { name: 'Pulmonary Medicine (TB & Chest)', value: 'Pulmonary Medicine (TB & Chest)' },
        { name: 'Radiology / Radio-diagnosis', value: 'Radiology / Radio-diagnosis' },
        { name: 'Sports Medicine', value: 'Sports Medicine' }
    ]},
    {degree: 'MS (Master of Surgery)',value: 'MS (Master of Surgery)', field:[
        { name: 'Anatomy', value: 'Anatomy' },
        { name: 'Cardiothoracic Surgery (super-speciality)', value: 'Cardiothoracic Surgery (super-speciality)' },
        { name: 'General Surgery', value: 'General Surgery' },
        { name: 'Neurosurgery (super-speciality after MS)', value: 'Neurosurgery (super-speciality after MS)' },
        { name: 'Obstetrics & Gynecology (sometimes under MD/MS)', value: 'Obstetrics & Gynecology (sometimes under MD/MS)' },
        { name: 'Ophthalmology', value: 'Ophthalmology' },
        { name: 'Orthopedics', value: 'Orthopedics' },
        { name: 'Otorhinolaryngology (ENT)', value: 'Otorhinolaryngology (ENT)' },
        { name: 'Pediatric Surgery (super-speciality)', value: 'Pediatric Surgery (super-speciality)' },
        { name: 'Plastic & Reconstructive Surgery (super-speciality)', value: 'Plastic & Reconstructive Surgery (super-speciality)' },
        { name: 'Urology (super-speciality after MS)', value: 'Urology (super-speciality after MS)' }
    ]},
    {degree: 'MDS (Master of Dental Surgery)',value: 'MDS (Master of Dental Surgery)', field:[
        { name: 'Conservative Dentistry & Endodontics', value: 'Conservative Dentistry & Endodontics' },
        { name: 'Oral & Maxillofacial Surgery', value: 'Oral & Maxillofacial Surgery' },
        { name: 'Oral Medicine & Radiology', value: 'Oral Medicine & Radiology' },
        { name: 'Oral Pathology & Microbiology', value: 'Oral Pathology & Microbiology' },
        { name: 'Orthodontics & Dentofacial Orthopaedics', value: 'Orthodontics & Dentofacial Orthopaedics' },
        { name: 'Pedodontics & Preventive Dentistry (Pediatric Dentistry)', value: 'Pedodontics & Preventive Dentistry (Pediatric Dentistry)' },
        { name: 'Periodontology (Periodontics)', value: 'Periodontology (Periodontics)' },
        { name: 'Prosthodontics and Crown & Bridge', value: 'Prosthodontics and Crown & Bridge' },
        { name: 'Public Health Dentistry', value: 'Public Health Dentistry' }
    ]},
    {degree: 'MCA (Master of Computer Applications)',value: 'MCA (Master of Computer Applications)', field:[
        {name: 'Computer Science',value: 'Computer Science'},
        {name: 'Information Technology (IT)',value: 'Information Technology (IT)'},
        {name: 'Artificial Intelligence & Machine Learning (AI & ML)',value: 'Artificial Intelligence & Machine Learning (AI & ML)'},
        {name: 'Data Science & Big Data Analytics',value: 'Data Science & Big Data Analytics'},
        {name: 'Cyber Security & Ethical Hacking',value: 'Cyber Security & Ethical Hacking'},
        {name: 'Cloud Computing',value: 'Cloud Computing'},
        {name: 'Internet of Things (IoT)',value: 'Internet of Things (IoT)'},
        {name: 'Blockchain Technology',value: 'Blockchain Technology'},
        {name: 'Augmented Reality (AR) & Virtual Reality (VR)',value: 'Augmented Reality (AR) & Virtual Reality (VR)'},
        {name: 'Game Development',value: 'Game Development'},
        {name: 'Animation & Multimedia',value: 'Animation & Multimedia'},
        {name: 'Database Management Systems (DBMS)',value: 'Database Management Systems (DBMS)'},
        {name: 'Web Development & Mobile App Development',value: 'Web Development & Mobile App Development'},
        {name: 'Software Engineering',value: 'Software Engineering'},
        {name: 'Networking & Security',value: 'Networking & Security'},
        {name: 'Financial Technology (FinTech)',value: 'Financial Technology (FinTech)'},
    ]},
    {degree: 'M.Arch (Master of Architecture)',value: 'M.Arch (Master of Architecture)', field:[
        { name: 'Architectural Design', value: 'Architectural Design' },
        { name: 'Building Construction & Materials', value: 'Building Construction & Materials' },
        { name: 'Building Services (HVAC, Lighting, Acoustics, Electrical, Plumbing)', value: 'Building Services (HVAC, Lighting, Acoustics, Electrical, Plumbing)' },
        { name: 'Computer-Aided Design (AutoCAD, Revit, BIM, 3D Modeling, Parametric Design)', value: 'Computer-Aided Design (AutoCAD, Revit, BIM, 3D Modeling, Parametric Design)' },
        { name: 'Construction Project Management', value: 'Construction Project Management' },
        { name: 'Environmental Studies (Climate-responsive design, Sustainability, Green Buildings)', value: 'Environmental Studies (Climate-responsive design, Sustainability, Green Buildings)' },
        { name: 'History of Architecture', value: 'History of Architecture' },
        { name: 'Interior Design & Space Planning', value: 'Interior Design & Space Planning' },
        { name: 'Landscape Architecture', value: 'Landscape Architecture' },
        { name: 'Professional Practice & Ethics', value: 'Professional Practice & Ethics' },
        { name: 'Structural Engineering for Architects', value: 'Structural Engineering for Architects' },
        { name: 'Theory of Architecture', value: 'Theory of Architecture' },
        { name: 'Town & Regional Planning', value: 'Town & Regional Planning' },
        { name: 'Urban Planning & Design', value: 'Urban Planning & Design' }
    ]},
    {degree: 'M.Com (Master of Commerce)',value: 'M. Com (Master of Commerce)', field:[
        {name: 'Accounting & Finance',value: 'Accounting & Finance'},
        {name: 'Banking & Insurance',value: 'Banking & Insurance'},
        {name: 'Auditing',value: 'Auditing'},
        {name: 'Taxation',value: 'Taxation'},
        {name: 'Economics & Business Studies',value: 'Economics & Business Studies'},
        {name: 'International Business',value: 'International Business'},
        {name: 'E-Commerce',value: 'E-Commerce'},
    ]},
    {degree: 'M.Pharm (Master of Pharmacy)',value: 'M.Pharm (Master of Pharmacy)', field:[
        { name: 'Hospital & Clinical Pharmacy', value: 'Hospital & Clinical Pharmacy' },
        { name: 'Pharmaceutical Analysis', value: 'Pharmaceutical Analysis' },
        { name: 'Pharmaceutical Biotechnology', value: 'Pharmaceutical Biotechnology' },
        { name: 'Pharmaceutical Chemistry', value: 'Pharmaceutical Chemistry' },
        { name: 'Pharmaceutics', value: 'Pharmaceutics' },
        { name: 'Pharmacognosy', value: 'Pharmacognosy' },
        { name: 'Pharmacology', value: 'Pharmacology' },
        { name: 'Regulatory Affairs & Pharmaceutical Jurisprudence', value: 'Regulatory Affairs & Pharmaceutical Jurisprudence' }
    ]},
    {degree: 'MPT (Master of Physiotherapy)',value: 'MPT (Master of Physiotherapy)', field:[
        { name: 'Cardiopulmonary Sciences', value: 'Cardiopulmonary Sciences' },
        { name: 'Community-Based Rehabilitation (CBR)', value: 'Community-Based Rehabilitation (CBR)' },
        { name: 'General & Rehabilitation Sciences', value: 'General & Rehabilitation Sciences' },
        { name: 'Geriatrics', value: 'Geriatrics' },
        { name: 'Hand Conditions / Hand Rehabilitation (less common, specialized)', value: 'Hand Conditions / Hand Rehabilitation (less common, specialized)' },
        { name: 'Musculoskeletal Sciences', value: 'Musculoskeletal Sciences' },
        { name: 'Neurology / Neurosciences', value: 'Neurology / Neurosciences' },
        { name: 'Obstetrics & Gynecology (Women’s Health)', value: 'Obstetrics & Gynecology (Women’s Health)' },
        { name: 'Orthopaedics', value: 'Orthopaedics' },
        { name: 'Pediatrics / Pediatric Physiotherapy', value: 'Pediatrics / Pediatric Physiotherapy' },
        { name: 'Sports Physiotherapy', value: 'Sports Physiotherapy' }
    ]},
    {degree: 'LL.M. (Master of Laws)',value: 'LL.M. (Master of Laws)', field:[]},
    {degree: 'M.Ed (Master of Education)',value: 'M.Ed (Master of Education)', field:[
        { name: 'Biology', value: 'Biology' },
        { name: 'Chemistry', value: 'Chemistry' },
        { name: 'Commerce', value: 'Commerce' },
        { name: 'Computer Science', value: 'Computer Science' },
        { name: 'Economics', value: 'Economics' },
        { name: 'English', value: 'English' },
        { name: 'Fine Arts', value: 'Fine Arts' },
        { name: 'Geography', value: 'Geography' },
        { name: 'Hindi', value: 'Hindi' },
        { name: 'History', value: 'History' },
        { name: 'Home Science', value: 'Home Science' },
        { name: 'Languages', value: 'Languages' },
        { name: 'Mathematics', value: 'Mathematics' },
        { name: 'Music Education', value: 'Music Education' },
        { name: 'Physical Education', value: 'Physical Education' },
        { name: 'Physics', value: 'Physics' },
        { name: 'Political Science', value: 'Political Science' },
        { name: 'Sanskrit', value: 'Sanskrit' },
        { name: 'Special Education', value: 'Special Education' }
    ]},
    {degree: 'MPEd (Master of Physical Education)',value: 'MPEd (Master of Physical Education)', field:[]},
    {degree: 'M.Des (Master of Design)',value: 'M.Des (Master of Design)', field:[]},
    {degree: 'MHM (Master of Hotel Management)',value: 'MHM (Master of Hotel Management)', field:[
        { name: 'Entrepreneurship in Hospitality', value: 'Entrepreneurship in Hospitality' },
        { name: 'Event Management', value: 'Event Management' },
        { name: 'Food & Beverage Service', value: 'Food & Beverage Service' },
        { name: 'Food Production (Culinary Arts / Kitchen Operations)', value: 'Food Production (Culinary Arts / Kitchen Operations)' },
        { name: 'Front Office Operations', value: 'Front Office Operations' },
        { name: 'Hospital Operations Management', value: 'Hospital Operations Management' },
        { name: 'Hospitality Accounting & Finance', value: 'Hospitality Accounting & Finance' },
        { name: 'Hospitality Information Systems (MIS/IT in Hospitality)', value: 'Hospitality Information Systems (MIS/IT in Hospitality)' },
        { name: 'Hospitality Law & Ethics', value: 'Hospitality Law & Ethics' },
        { name: 'Hospitality Marketing & Sales', value: 'Hospitality Marketing & Sales' },
        { name: 'Housekeeping Operations', value: 'Housekeeping Operations' },
        { name: 'Human Resource Management in Hospitality', value: 'Human Resource Management in Hospitality' },
        { name: 'Resort & Club Management', value: 'Resort & Club Management' },
        { name: 'Travel & Tourism Management', value: 'Travel & Tourism Management' }
    ]},
    {degree: 'Ph.D. (Doctor of Philosophy)',value: 'Ph.D. (Doctor of Philosophy)', field:[
        { name: 'Artificial Intelligence / Data Science', value: 'Artificial Intelligence / Data Science' },
        { name: 'Biology', value: 'Biology' },
        { name: 'Biotechnology', value: 'Biotechnology' },
        { name: 'Business Administration', value: 'Business Administration' },
        { name: 'Chemistry', value: 'Chemistry' },
        { name: 'Civil Engineering', value: 'Civil Engineering' },
        { name: 'Commerce', value: 'Commerce' },
        { name: 'Computer Science & Engineering', value: 'Computer Science & Engineering' },
        { name: 'Constitutional Law', value: 'Constitutional Law' },
        { name: 'Corporate Law', value: 'Corporate Law' },
        { name: 'Criminal Law', value: 'Criminal Law' },
        { name: 'Cultural Studies', value: 'Cultural Studies' },
        { name: 'Curriculum Studies', value: 'Curriculum Studies' },
        { name: 'Economics', value: 'Economics' },
        { name: 'Educational Technology', value: 'Educational Technology' },
        { name: 'Electrical Engineering', value: 'Electrical Engineering' },
        { name: 'Electronics & Communication', value: 'Electronics & Communication' },
        { name: 'English Literature', value: 'English Literature' },
        { name: 'Environmental Science', value: 'Environmental Science' },
        { name: 'Environmental Studies', value: 'Environmental Studies' },
        { name: 'Gender Studies', value: 'Gender Studies' },
        { name: 'Geology', value: 'Geology' },
        { name: 'History', value: 'History' },
        { name: 'Information Technology', value: 'Information Technology' },
        { name: 'International Law', value: 'International Law' },
        { name: 'Management Studies (HR, Marketing, Finance, Operations)', value: 'Management Studies (HR, Marketing, Finance, Operations)' },
        { name: 'Mathematics', value: 'Mathematics' },
        { name: 'Mechanical Engineering', value: 'Mechanical Engineering' },
        { name: 'Medicine (Ph.D. in Medical Sciences)', value: 'Medicine (Ph.D. in Medical Sciences)' },
        { name: 'Nursing', value: 'Nursing' },
        { name: 'Pharmacy (Ph.D. in Pharmaceutics, Pharmacology, Pharmacognosy, etc.)', value: 'Pharmacy (Ph.D. in Pharmaceutics, Pharmacology, Pharmacognosy, etc.)' },
        { name: 'Philosophy', value: 'Philosophy' },
        { name: 'Physics', value: 'Physics' },
        { name: 'Political Science', value: 'Political Science' },
        { name: 'Psychology', value: 'Psychology' },
        { name: 'Public Health', value: 'Public Health' },
        { name: 'Social Work', value: 'Social Work' },
        { name: 'Sociology', value: 'Sociology' },
        { name: 'Teacher Education', value: 'Teacher Education' }
    ]},
    {degree: 'D.Sc. (Doctor of Science)',value: 'D.Sc. (Doctor of Science)', field:[
        { name: 'Aerospace Engineering', value: 'Aerospace Engineering' },
        { name: 'Agriculture', value: 'Agriculture' },
        { name: 'Atmospheric Sciences', value: 'Atmospheric Sciences' },
        { name: 'Biotechnology', value: 'Biotechnology' },
        { name: 'Botany', value: 'Botany' },
        { name: 'Chemical Engineering', value: 'Chemical Engineering' },
        { name: 'Chemistry', value: 'Chemistry' },
        { name: 'Civil Engineering', value: 'Civil Engineering' },
        { name: 'Computer Science / Information Technology', value: 'Computer Science / Information Technology' },
        { name: 'Earth Sciences / Geology', value: 'Earth Sciences / Geology' },
        { name: 'Electrical Engineering', value: 'Electrical Engineering' },
        { name: 'Electronics', value: 'Electronics' },
        { name: 'Electronics & Communication', value: 'Electronics & Communication' },
        { name: 'Environmental Science', value: 'Environmental Science' },
        { name: 'Fisheries', value: 'Fisheries' },
        { name: 'Forestry', value: 'Forestry' },
        { name: 'Horticulture', value: 'Horticulture' },
        { name: 'Mathematics', value: 'Mathematics' },
        { name: 'Mechanical Engineering', value: 'Mechanical Engineering' },
        { name: 'Medicine', value: 'Medicine' },
        { name: 'Metallurgy', value: 'Metallurgy' },
        { name: 'Oceanography', value: 'Oceanography' },
        { name: 'Pharmacy / Pharmaceutical Sciences', value: 'Pharmacy / Pharmaceutical Sciences' },
        { name: 'Physics', value: 'Physics' },
        { name: 'Public Health', value: 'Public Health' },
        { name: 'Statistics', value: 'Statistics' },
        { name: 'Surgery', value: 'Surgery' },
        { name: 'Veterinary Science', value: 'Veterinary Science' },
        { name: 'Zoology', value: 'Zoology' }
    ]},
    {degree: 'D.Litt. (Doctor of Literature)',value: 'D.Litt. (Doctor of Literature)', field:[]},
    {degree: 'Polytechnic Diplomas (Engineering, IT, Electronics, etc.)',value: 'Polytechnic Diplomas (Engineering, IT, Electronics, etc.)', field:[
        { name: 'Aeronautical Engineering', value: 'Aeronautical Engineering' },
        { name: 'Agricultural Engineering', value: 'Agricultural Engineering' },
        { name: 'Architecture Assistantship', value: 'Architecture Assistantship' },
        { name: 'Automobile Engineering', value: 'Automobile Engineering' },
        { name: 'Ceramic Technology', value: 'Ceramic Technology' },
        { name: 'Chemical Engineering', value: 'Chemical Engineering' },
        { name: 'Civil Engineering', value: 'Civil Engineering' },
        { name: 'Commercial Practice / Modern Office Practice (MOP)', value: 'Commercial Practice / Modern Office Practice (MOP)' },
        { name: 'Computer Engineering / Computer Science & Engineering (CSE)', value: 'Computer Engineering / Computer Science & Engineering (CSE)' },
        { name: 'Electrical Engineering', value: 'Electrical Engineering' },
        { name: 'Electronics & Communication Engineering (ECE)', value: 'Electronics & Communication Engineering (ECE)' },
        { name: 'Fashion Design / Garment Technology', value: 'Fashion Design / Garment Technology' },
        { name: 'Food Technology', value: 'Food Technology' },
        { name: 'Hotel Management & Catering Technology', value: 'Hotel Management & Catering Technology' },
        { name: 'Information Technology (IT)', value: 'Information Technology (IT)' },
        { name: 'Instrumentation & Control Engineering', value: 'Instrumentation & Control Engineering' },
        { name: 'Interior Design', value: 'Interior Design' },
        { name: 'Library & Information Science', value: 'Library & Information Science' },
        { name: 'Marine Engineering', value: 'Marine Engineering' },
        { name: 'Mechanical Engineering', value: 'Mechanical Engineering' },
        { name: 'Mechatronics Engineering', value: 'Mechatronics Engineering' },
        { name: 'Medical Laboratory Technology (MLT)', value: 'Medical Laboratory Technology (MLT)' },
        { name: 'Metallurgical Engineering', value: 'Metallurgical Engineering' },
        { name: 'Mining Engineering', value: 'Mining Engineering' },
        { name: 'Petroleum Engineering', value: 'Petroleum Engineering' },
        { name: 'Pharmacy (D.Pharm)', value: 'Pharmacy (D.Pharm)' },
        { name: 'Plastic Engineering', value: 'Plastic Engineering' },
        { name: 'Printing Technology', value: 'Printing Technology' },
        { name: 'Production Engineering', value: 'Production Engineering' },
        { name: 'Rubber Technology', value: 'Rubber Technology' },
        { name: 'Textile Technology', value: 'Textile Technology' }
    ]},
    {degree: 'Diploma in Pharmacy (D.Pharm)',value: 'Diploma in Pharmacy (D.Pharm)', field:[]},
    {degree: 'Nursing Diplomas (GNM, ANM)',value: 'Nursing Diplomas (GNM, ANM)', field:[]},
    {degree: 'Teacher Training Diplomas (D.Ed, BTC)',value: 'Teacher Training Diplomas (D.Ed, BTC)', field:[
        { name: 'D.Ed Special Education (Approved by RCI – Rehabilitation Council of India)', value: 'D.Ed Special Education (Approved by RCI – Rehabilitation Council of India)' },
        { name: 'D.El.Ed (Diploma in Elementary Education)', value: 'D.El.Ed (Diploma in Elementary Education)' },
        { name: 'D.T.Ed (Diploma in Teacher Education)', value: 'D.T.Ed (Diploma in Teacher Education)' },
        { name: 'Pre-Primary / Nursery Teacher Training (NTT / ECCE Diploma)', value: 'Pre-Primary / Nursery Teacher Training (NTT / ECCE Diploma)' }
    ]},
    {degree: 'Hotel Management Diplomas',value: 'Hotel Management Diplomas', field:[
        { name: 'Event Management', value: 'Event Management' },
        { name: 'Food & Beverage Service', value: 'Food & Beverage Service' },
        { name: 'Food Production / Culinary Arts', value: 'Food Production / Culinary Arts' },
        { name: 'Front Office Management', value: 'Front Office Management' },
        { name: 'Hospitality & Tourism Management', value: 'Hospitality & Tourism Management' },
        { name: 'Hospitality Finance & Accounting', value: 'Hospitality Finance & Accounting' },
        { name: 'Hospitality Information Systems', value: 'Hospitality Information Systems' },
        { name: 'Hospitality Sales & Marketing', value: 'Hospitality Sales & Marketing' },
        { name: 'Housekeeping Management', value: 'Housekeeping Management' },
        { name: 'Resort & Luxury Management', value: 'Resort & Luxury Management' }
    ]},
    {degree: 'Short-term certifications',value: 'Short-term certifications', field:[]},
  ]